name: Terraform Provisioning

on:
  workflow_call:

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .deployment/staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
