name: Staging Pipeline

on:
  push:
    branches:
      - 'stg/v*'
   
jobs:

  terraform:
    uses: ./.github/workflows/staging-provision.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}


  build:
    uses: ./.github/workflows/staging-build.yml
    needs: terraform
    with:
      version: ${{ github.ref_name }}

  test:
    uses: ./.github/workflows/staging-test.yml
    needs: build
    secrets:
      ssh_key: ${{ secrets.SSH_KEY }}