name: Test DMZ on Remote

on:
  workflow_call:
    secrets:
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: dmz-binary
          path: target/release

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ssh_key }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Verify SSH Access
        run: .pipeline/check-ready.sh

      - name: Install on Remote
        run: .pipeline/install-on-test.sh

      - name: Smoke Test
        run: .pipeline/smoke-test.sh




     
