name: Test DMZ on Remote

on:
  workflow_call:
    secrets:
      ssh_key:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4

      - name: Download Binary
        uses: actions/download-artifact@v4
        with:
          name: dmz-binary
          path: target/release






     
